spring.application.name=renting
spring.datasource.url=jdbc:sqlserver://163.178.173.130;databaseName=VideoRent_C4J816_II2026;encrypt=true;trustServerCertificate=true;

#CONFIGURACION DE LA CONEXION A LA BASE DE DATOS
spring.datasource.username=Lenguajes
spring.datasource.password=lenguajesparaiso2025
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

#context path
server.servlet.context-path=/renting
server.port=8084
